dev:
  xcworkspace: /Users/wellington/Projetos/cnqs-calabash/desafio-ios/ConcreteTest.xcworkspace/
  scheme: ConcreteTest-cal
  configuration: Debug
  export_path: /Users/wellington/Projetos/cnqs-calabash/build

jenkins:
  xcworkspace: <%= ENV['WORKSPACE']%>/Project.xcworkspace
  scheme: TargetName
  configuration: Debug
  destination: "Any_platform_or_device_that_you_want"
  export_path: <%= ENV['WORKSPACE']%>/releases/normal
